clickhouse:
  fullnameOverride: clickhouse
  clickhouse:
    imageVersion: "19.16"

kafka:
  fullnameOverride: kafka-confluent
  replicaCount: 3
  allowPlaintextListener: true
  defaultReplicationFactor: 3
  offsetsTopicReplicationFactor: 3
  transactionStateLogReplicationFactor: 3
  transactionStateLogMinIsr: 3

  zookeeper:
    fullnameOverride: zookeeper

redis:
  enabled: true
  fullnameOverride: redis
  
  usePassword: false
  cluster:
    slaveCount: 2
  master:
    nodeSelector: {}
    resources: {}
    # priorityClassName: 
  slave:
    nodeSelector: {}
    resources: {}
    # priorityClassName: 

# redis-ha:
#   enabled: false
#   redis:
#     masterGroupName: master
#     resources: {}
#   sentinel:
#     resources: {}
#   persistentVolume:
#     enabled: true
#     size: 20Gi

global:
  postgresql:
    postgresqlPassword: i@ZBAsFoU4gDz_qDJVX2W8
    postgresqlDatabase: sentry

postgresql:
  enabled: true
  fullnameOverride: postgres
  password: i@ZBAsFoU4gDz_qDJVX2W8 
  # postgresqlUsername: sentry
  postgresqlPassword: i@ZBAsFoU4gDz_qDJVX2W8 
  # password: i@ZBAsFoU4gDz_qDJVX2W8
  postgresqlDatabase: sentry

  replication:
    enabled: true
    slaveReplicas: 2
    synchronousCommit: "on"
    numSynchronousReplicas: 1

rabbitmq-ha:
  enabled: true
  forceBoot: true
  replicaCount: 3
  fullnameOverride: rabbitmq-ha
  rabbitmqErlangCookie: pHgpy3Q6adTskzAT6bLHCFqFTF7lMxhA
  rabbitmqUsername: guest
  rabbitmqPassword: guest

  podDisruptionBudget:
    minAvailable: 1
  
  persistentVolume:
    enabled: true
  resources: {}
  # rabbitmqMemoryHighWatermark: 600MB
  # rabbitmqMemoryHighWatermarkType: absolute

  definitions:
    policies: |-
     {
       "name": "ha-all",
       "pattern": "^((?!celeryev.*).)*$",
       "vhost": "/",
       "definition": {
         "ha-mode": "all",
         "ha-sync-mode": "automatic",
         "ha-sync-batch-size": 1
       }
     }