apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.prefix" . }}snuba
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
data:
  SNUBA_SETTINGS: docker
  CLICKHOUSE_HOST: "{{ template "sentry.clickhouse.host" . }}"
  CLICKHOUSE_PORT: "{{ template "sentry.clickhouse.port" . }}"
  REDIS_HOST: "{{ default (include "sentry.redis.host" .) .Values.redis.hostOverride }}"
  {{ if .Values.redis.usePassword }}
  REDIS_PASSWORD: {{ .Values.redis.password }}
  {{- end -}}
  DEFAULT_BROKERS: "{{ printf "%s:%s" (include "sentry.kafka.host" .) (include "sentry.kafka.port" .) }}"
